service:
  name: crud-serverless

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  createUser:
    handler: src/handler.createUser
    events:
      - http:
          method: post
          path: users

  listAllUsers:
    handler: src/handler.listAllUsers
    events:
      - http:
          method: get
          path: users

  showUser:
    handler: src/handler.showUser
    events:
      - http:
          method: get
          path: users/{id}

  updateUser:
    handler: src/handler.updateUser
    events:
      - http:
          method: put
          path: users/{id}
